### DISCUSSION TITLE
Activate dependabot

### DISCUSSION THREAD

**Discussion by marcospereira** [casid/jte#291] [Ideas]
Hey @casid,

While jte is pretty minimal regarding dependencies for the library (which is fantastic), I notice a few Maven plugins lagging behind. While having such updates is mainly in the nice-to-have category, the work to maintain them is also pretty minimal. The project can use [Dependabot](https://docs.github.com/en/code-security/dependabot) to open pull requests automatically.

For example, the following configuration:

```yaml
version: 2
updates:
  - package-ecosystem: maven
    schedule:
      interval: "weekly"
    directory: /
    rebase-strategy: auto
    open-pull-requests-limit: 10
    groups:
      maven-patch-updates:
        update-types: ["patch"]
```

It reduces a lot of the noise this way:

1. Runs weekly, which seems reasonable for jte
2. Limit the number of open pull requests
3. Automatically rebase pull requests as other changes get merged
4. Group patch updates together

WDYT?

**Comment by marcospereira** [comment]
Oh, just realized we can add Github Actions there, too:

```yaml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    rebase-strategy: auto
    schedule:
      interval: "weekly"
      day: "sunday"
    commit-message:
      prefix: "[github-actions]"
  - package-ecosystem: maven
    schedule:
      interval: "weekly"
    directory: /
    rebase-strategy: auto
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[maven]"
    groups:
      maven-patch-updates:
        update-types: ["patch"]
```
